#!/usr/bin/env bash
set -euo pipefail

# Lean, deterministic codebase-map generator (no LLM, no network).
#
# Writes docs/CODEBASE_MAP.md from the file tree + Swift file header comments,
# so `codex-agent start ... --map` always has fresh architectural context.
# This is the cheap, automatable substitute for the full `/cartographer` plugin;
# run /cartographer manually when you want the rich, narrated version.
#
# Usage: build-map.sh [repo-root]   (defaults to git toplevel, else cwd)

ROOT="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT"

OUT="docs/CODEBASE_MAP.md"
mkdir -p docs

HEAD_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo 'n/a')"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'n/a')"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Search roots for Swift sources: SPM packages + the app target dirs.
# Excludes build artifacts, .git, and DerivedData.
swift_files() {
  find . \
    -type d \( -name .git -o -name .build -o -name DerivedData -o -name .swiftpm \) -prune -o \
    -type f -name '*.swift' ! -name 'Package.swift' -print 2>/dev/null | sed 's|^\./||' | sort
}

# Extract a one-line purpose from a Swift file's leading `//` header block.
# Skips the filename line and the bare project-name line; joins the first two
# substantive comment lines. Prints "(no header)" when there is no doc block.
purpose_of() {
  awk '
    /^[[:space:]]*\/\// {
      line = $0
      sub(/^[[:space:]]*\/\/[[:space:]]?/, "", line)
      comments[++n] = line
      next
    }
    /^[[:space:]]*$/ { if (!seen) next; else exit }
    { exit }
    END {
      out = ""; cnt = 0
      for (i = 1; i <= n; i++) {
        c = comments[i]
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", c)
        if (c == "") continue
        if (c ~ /\.swift$/) continue
        if (c ~ /^OwnFrame/) continue   # Xcode module/target-name line
        if (c ~ /^Created by /) continue         # Xcode author boilerplate
        if (c ~ /^Copyright/) continue
        out = (out == "") ? c : out " " c
        if (++cnt >= 2) break
      }
      print (out == "" ? "(no header)" : out)
    }
  ' "$1"
}

{
  echo "---"
  echo "generated_by: build-map.sh (lean, deterministic)"
  echo "generated_at: $STAMP"
  echo "git: $BRANCH @ $HEAD_SHA"
  echo "---"
  echo
  echo "# Codebase Map — ImmichSlideshow"
  echo
  echo "> Auto-generated by \`.claude/scripts/build-map.sh\` on session start."
  echo "> For narrative architecture see \`CLAUDE.md\`; run \`/cartographer\` for a richer map."
  echo
  echo "## SPM packages"
  echo
  if compgen -G "Packages/*/Package.swift" > /dev/null; then
    for pkg in Packages/*/Package.swift; do
      dir="$(dirname "$pkg")"
      name="$(basename "$dir")"
      echo "### $name (\`$dir\`)"
      echo
      products="$(grep -oE '(library|executable)\(name: "[^"]+"' "$pkg" | sed -E 's/.*name: "([^"]+)".*/\1/' | sort -u | paste -sd', ' - || true)"
      deps="$(grep -oE '\.package\((path|url): "[^"]+"' "$pkg" | sed -E 's/.*: "([^"]+)".*/\1/' | sort -u | paste -sd', ' - || true)"
      [ -n "$products" ] && echo "- Products: $products"
      [ -n "$deps" ] && echo "- Package deps: $deps"
      echo
    done
  else
    echo "_None found._"
    echo
  fi
  echo "## File index"
  echo
  echo "One line per Swift file, taken from its header comment."
  echo
  prev_dir=""
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    d="$(dirname "$f")"
    if [ "$d" != "$prev_dir" ]; then
      echo
      echo "#### \`$d/\`"
      prev_dir="$d"
    fi
    echo "- \`$(basename "$f")\` — $(purpose_of "$f")"
  done < <(swift_files)
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines, $BRANCH @ $HEAD_SHA)"
